#!/bin/bash
#
# publish-report.sh
# Publish test report to GitHub Pages (only if tests pass)
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
QA_DIR="$(dirname "$SCRIPT_DIR")"
REPO_ROOT="$(dirname "$QA_DIR")"
RESULTS_FILE="$QA_DIR/reports/results.json"
DOCS_DIR="$REPO_ROOT/docs/qa-report"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "=========================================="
echo "  Blaze QA - Publish Report to GitHub Pages"
echo "=========================================="
echo ""

# Check if results file exists
if [ ! -f "$RESULTS_FILE" ]; then
    echo -e "${RED}Error: No test results found at $RESULTS_FILE${NC}"
    echo "Run 'npm test' first to generate results."
    exit 1
fi

# Check for test failures using jq
if command -v jq &> /dev/null; then
    FAILURES=$(jq '[.suites[].specs[].tests[].results[].status] | map(select(. == "failed")) | length' "$RESULTS_FILE" 2>/dev/null || echo "0")

    if [ "$FAILURES" -gt 0 ]; then
        echo -e "${RED}Error: $FAILURES test(s) failed.${NC}"
        echo "Fix all failures before publishing report."
        echo "Run 'npm run report' to view failure details."
        exit 1
    fi

    TOTAL_TESTS=$(jq '[.suites[].specs[].tests[]] | length' "$RESULTS_FILE" 2>/dev/null || echo "?")
    PASSED_TESTS=$(jq '[.suites[].specs[].tests[].results[].status] | map(select(. == "passed" or . == "expected")) | length' "$RESULTS_FILE" 2>/dev/null || echo "?")

    echo -e "${GREEN}All tests passed ($PASSED_TESTS/$TOTAL_TESTS)${NC}"
else
    echo -e "${YELLOW}Warning: jq not installed. Skipping failure check.${NC}"
    echo "Install with: brew install jq"
fi

# Check if HTML report exists
if [ ! -d "$QA_DIR/reports/html" ]; then
    echo -e "${RED}Error: HTML report not found at $QA_DIR/reports/html${NC}"
    exit 1
fi

# Create docs directory
mkdir -p "$DOCS_DIR"

# Get timestamp
TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")

# Copy report to docs folder
echo ""
echo "Copying report to $DOCS_DIR..."
rm -rf "$DOCS_DIR"/*
cp -r "$QA_DIR/reports/html"/* "$DOCS_DIR/"

# Inject navigation bar into the report
echo "Injecting navigation bar..."
REPORT_INDEX="$DOCS_DIR/index.html"
if [ -f "$REPORT_INDEX" ]; then
    python3 << PYEOF
import re

nav_html = '''<div id="blaze-nav" style="background:#0d1117;border-bottom:1px solid #30363d;padding:12px 24px;display:flex;align-items:center;justify-content:space-between;font-family:-apple-system,BlinkMacSystemFont,sans-serif;position:sticky;top:0;z-index:9999;"><div style="display:flex;align-items:center;gap:16px;"><a href="../" style="color:#e6edf3;text-decoration:none;font-weight:600;font-size:14px;">← Back to Dashboard</a><span style="color:#30363d;">|</span><span style="color:#8b949e;font-size:13px;">birdbusta.net</span></div><div style="display:flex;align-items:center;gap:12px;"><span style="color:#3fb950;font-size:13px;">$TIMESTAMP</span><a href="https://github.com/blaze-commerce/claude-wpm" target="_blank" style="color:#58a6ff;text-decoration:none;font-size:13px;">GitHub</a></div></div>'''

with open('$REPORT_INDEX', 'r') as f:
    content = f.read()

if 'blaze-nav' not in content:
    content = re.sub(r'(<body[^>]*>)', r'\1' + nav_html, content, count=1)
    with open('$REPORT_INDEX', 'w') as f:
        f.write(content)
    print("Navigation bar added.")
else:
    print("Navigation bar already exists.")
PYEOF
fi

# Commit and push
cd "$REPO_ROOT"
git add docs/qa-report

# Check if there are changes to commit
if git diff --staged --quiet; then
    echo -e "${YELLOW}No changes to report. Already up to date.${NC}"
    exit 0
fi

git commit -m "docs(qa): publish test report - $TIMESTAMP

Tests: $PASSED_TESTS/$TOTAL_TESTS passed
Generated by Blaze QA Framework"

echo ""
echo "Pushing to origin..."
git push origin main

echo ""
echo -e "${GREEN}==========================================${NC}"
echo -e "${GREEN}  Report Published Successfully!${NC}"
echo -e "${GREEN}==========================================${NC}"
echo ""
echo "View at: https://blaze-commerce.github.io/claude-wpm/qa-report/"
echo ""
